import React from 'react';
import ReactMarkdown from 'react-markdown';
import { jsPDF } from 'jspdf';
import { Copy, Download, RefreshCw, Check, Mail, MessageSquare, ShieldCheck, AlertTriangle, ShieldAlert, RotateCcw } from 'lucide-react';
import { GeneratedContent, ComplianceState } from '../types';

interface ResultViewProps {
  data: GeneratedContent;
  onReset: () => void;
  onCheckCompliance: () => void;
  complianceState: ComplianceState;
}

export const ResultView: React.FC<ResultViewProps> = ({ 
  data, 
  onReset, 
  onCheckCompliance,
  complianceState
}) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    const fullText = `Subject: ${data.subjectLines[0]}\n\n${data.content}`;
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(10);
    doc.text("Generated by IntcommAI", 10, 10);
    
    doc.setFontSize(16);
    doc.text("Internal Communication", 10, 20);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Subject Options:", 10, 30);
    doc.setFont("helvetica", "normal");
    
    let y = 40;
    data.subjectLines.forEach((sub, i) => {
      doc.text(`${i + 1}. ${sub}`, 15, y);
      y += 8;
    });

    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Content:", 10, y);
    doc.setFont("helvetica", "normal");
    y += 10;
    
    const splitText = doc.splitTextToSize(data.content, 180);
    doc.text(splitText, 10, y);
    
    doc.save("internal-comm.pdf");
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden h-full flex flex-col">
      <div className="p-4 border-b border-slate-100 bg-slate-50 flex items-center justify-between">
        <h2 className="font-semibold text-slate-800 flex items-center gap-2">
          <Mail className="w-4 h-4 text-emerald-500" />
          Ready to Send
        </h2>
        <div className="flex gap-2">
           <button 
            onClick={onReset}
            className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-slate-100 rounded-lg transition-colors"
            title="Create New"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
          <button 
            onClick={handleExportPDF}
            className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-slate-100 rounded-lg transition-colors"
            title="Export PDF"
          >
            <Download className="w-4 h-4" />
          </button>
          <button 
            onClick={handleCopy}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-all ${
              copied 
                ? 'bg-green-100 text-green-700' 
                : 'bg-indigo-50 text-indigo-600 hover:bg-indigo-100'
            }`}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied' : 'Copy Text'}
          </button>
        </div>
      </div>

      <div className="p-6 overflow-y-auto flex-1 bg-white">
        
        {/* Subject Lines */}
        <div className="mb-8">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">
            Subject Line Options
          </h3>
          <div className="space-y-2">
            {data.subjectLines.map((subject, idx) => (
              <div key={idx} className="group flex items-center justify-between p-3 rounded-lg border border-slate-200 hover:border-indigo-300 hover:shadow-sm bg-slate-50/50 hover:bg-white transition-all cursor-pointer"
                   onClick={() => {navigator.clipboard.writeText(subject)}}>
                <span className="text-slate-700 font-medium text-sm">{subject}</span>
                <Copy className="w-3 h-3 text-slate-300 group-hover:text-indigo-400 opacity-0 group-hover:opacity-100 transition-opacity" />
              </div>
            ))}
          </div>
        </div>

        {/* Content Body */}
        <div className="mb-8">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">
            Email Body
          </h3>
          <div className="prose prose-slate prose-lg max-w-none p-8 border-2 border-slate-200 rounded-xl bg-white shadow-md">
            <ReactMarkdown 
              components={{
                /* eslint-disable @typescript-eslint/no-unused-vars */
                h1: ({node, ...props}) => <h1 className="text-2xl font-bold text-slate-900 mb-4 pb-2 border-b-2 border-slate-200" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-xl font-bold text-slate-800 mt-6 mb-3" {...props} />,
                h3: ({node, ...props}) => <h3 className="text-lg font-semibold text-slate-700 mt-4 mb-2" {...props} />,
                p: ({node, ...props}) => <p className="text-slate-700 leading-relaxed mb-4" {...props} />,
                ul: ({node, ...props}) => <ul className="list-disc list-inside space-y-2 mb-4 ml-2" {...props} />,
                ol: ({node, ...props}) => <ol className="list-decimal list-inside space-y-2 mb-4 ml-2" {...props} />,
                li: ({node, ...props}) => <li className="text-slate-700 leading-relaxed" {...props} />,
                strong: ({node, ...props}) => <strong className="font-bold text-slate-900" {...props} />,
                em: ({node, ...props}) => <em className="italic text-slate-600" {...props} />,
                hr: ({node, ...props}) => <hr className="my-6 border-t-2 border-slate-200" {...props} />,
                blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-indigo-500 pl-4 italic text-slate-600 my-4" {...props} />,
                /* eslint-enable @typescript-eslint/no-unused-vars */
              }}
            >{data.content}</ReactMarkdown>
          </div>
        </div>

        {/* Summary Card */}
        <div className="mb-8 p-4 bg-indigo-50 rounded-lg border border-indigo-100">
           <div className="flex gap-3">
             <div className="mt-1">
                <MessageSquare className="w-5 h-5 text-indigo-500" />
             </div>
             <div>
               <h4 className="text-sm font-bold text-indigo-900 mb-1">Summary & Goal</h4>
               <p className="text-sm text-indigo-700 leading-relaxed mb-2">{data.summary}</p>
               <div className="text-xs font-medium text-indigo-600 bg-white/50 px-2 py-1 rounded inline-block">
                 CTA: {data.callToAction}
               </div>
             </div>
           </div>
        </div>

        {/* Compliance Section */}
        <div className="mb-6">
          {complianceState.status === 'idle' && (
            <button 
              onClick={onCheckCompliance}
              className="w-full py-3 border-2 border-dashed border-slate-200 rounded-lg text-slate-500 font-medium hover:border-indigo-300 hover:text-indigo-600 hover:bg-indigo-50/30 transition-all flex items-center justify-center gap-2"
            >
              <ShieldCheck className="w-5 h-5" />
              Run Compliance & Brand Voice Check
            </button>
          )}

          {complianceState.status === 'checking' && (
             <div className="w-full py-3 border border-indigo-100 bg-indigo-50/50 rounded-lg flex items-center justify-center gap-3">
               <div className="w-5 h-5 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
               <span className="text-indigo-700 font-medium">Analyzing tone and risks...</span>
             </div>
          )}

          {complianceState.status === 'error' && (
            <div className="w-full py-3 border border-red-200 bg-red-50 rounded-lg flex items-center justify-between px-4">
              <div className="flex items-center gap-2 text-red-700">
                <AlertTriangle className="w-5 h-5" />
                <span className="text-sm font-medium">{complianceState.error || "Compliance check failed. Please try again."}</span>
              </div>
              <button 
                onClick={onCheckCompliance} 
                className="text-xs font-semibold text-red-700 hover:text-red-900 flex items-center gap-1 bg-white px-2 py-1 rounded border border-red-200 hover:bg-red-50"
              >
                <RotateCcw className="w-3 h-3" />
                Retry
              </button>
            </div>
          )}

          {complianceState.status === 'success' && complianceState.data && (
            <div className={`rounded-lg border p-4 ${
              complianceState.data.status === 'Safe' ? 'bg-emerald-50 border-emerald-200' :
              complianceState.data.status === 'Warning' ? 'bg-amber-50 border-amber-200' :
              'bg-red-50 border-red-200'
            }`}>
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className={`p-2 rounded-full ${
                    complianceState.data.status === 'Safe' ? 'bg-emerald-100 text-emerald-600' :
                    complianceState.data.status === 'Warning' ? 'bg-amber-100 text-amber-600' :
                    'bg-red-100 text-red-600'
                  }`}>
                    {complianceState.data.status === 'Safe' ? <ShieldCheck className="w-5 h-5" /> : 
                     complianceState.data.status === 'Warning' ? <AlertTriangle className="w-5 h-5" /> : 
                     <ShieldAlert className="w-5 h-5" />}
                  </div>
                  <div>
                    <h3 className={`font-bold ${
                       complianceState.data.status === 'Safe' ? 'text-emerald-800' :
                       complianceState.data.status === 'Warning' ? 'text-amber-800' :
                       'text-red-800'
                    }`}>
                      Compliance Score: {complianceState.data.score}/100
                    </h3>
                    <p className="text-sm text-slate-600">{complianceState.data.overallFeedback}</p>
                  </div>
                </div>
              </div>

              {complianceState.data.issues.length > 0 && (
                <div className="mt-3 space-y-2 bg-white/60 rounded-lg p-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Detected Issues</h4>
                  {complianceState.data.issues.map((issue, idx) => (
                    <div key={idx} className="text-sm border-l-2 pl-3 py-1 border-slate-300">
                      <p className="font-semibold text-slate-800">&quot;{issue.phrase}&quot;</p>
                      <p className="text-slate-600 text-xs mb-1">{issue.reason}</p>
                      <p className="text-indigo-600 text-xs font-medium">Suggestion: {issue.suggestion}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};